### ISSUE TITLE
How to initialize with angular/fire

### ISSUE THREAD

**Issue by skibaalex** [codediodeio/geofirex#130]
I have firebase initialized at the app.module

`AngularFireModule.initializeApp(environment.firebaseConfig),`

how do i pass that instance in another component?

**Comment by skibaalex** [comment]
found a solution 

`constructor(private db: AngularFirestore) {}
  geo = geofirex.init(this.db.firestore.app.firebase_);`

**Comment by skibaalex** [comment]
unable to build.
everything is working fine in development but im getting this error

> Property 'firebase_' does not exist on type 'App'.

**Comment by technbuzz** [comment]
Assuming that **@angular/fire** is already initialized at `module` level. You can just import firebase and use like below:

```
import firebase from 'firebase/app';
import * as geofirex from "geofirex";

ngOnInit() {
      const geo = geofirex.init(firebase)
}
```

**Comment by skibaalex** [comment]
Thanks thats what i did
