### ISSUE TITLE
cannot find module geojson

### ISSUE THREAD

**Issue by shriharip** [codediodeio/geofirex#2]
import { Point, Feature } from 'geojson'; inside the dist geohash.ts

Hi Jeff,

Followed the readme and added geofirex in my ionic project .
On ionic serve I get 

TypeScript ERROR
Cannot find module 'geojson'.

  | import { firestore } from './interfaces';
-- | --
  | import { Point, Feature } from 'geojson';
  | export declare type Latitude = number;

**Comment by codediodeio** [comment]
Ah, this is because they are external types. I have a fix that will be on the next release v0.0.5 later today.

**Comment by codediodeio** [comment]
Fixed, install the latest version and you should be good to go :+1:
