### ISSUE TITLE
Cannot read property apply of undefined

### ISSUE THREAD

**Issue by shriharip** [codediodeio/geofirex#4]
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'apply' of undefined
TypeError: Cannot read property 'apply' of undefined
    at GeoFireCollectionRef.within (index.esm.js:1549)

this refers to the line within the GeoQueries 

  GeoFireCollectionRef.prototype.within = 
.......
        var combo = combineLatest.apply(void 0, queries).pipe(map(function (arr)

My component code;

        const lat = data['position'].geopoint.latitude;
        const lng = data['position'].geopoint.longitude;
       const center = this.geo.point(lat,lng);
       const radius = 2;
        const field = 'position';
       const locRef = this.geo.collection('locations');

my position data
 {position: {…}}position: 
geohash: "u3bvhj5pc"
geopoint: GeoPoint {_lat: 55.7514828, _long: 12.4846695}
__proto__: Object

the constant center 
![image](https://user-images.githubusercontent.com/3909110/42570069-f74d89e6-8512-11e8-8198-cecfb7099a35.png)

**Comment by codediodeio** [comment]
Does this error happen when you call `within` to make a geoquery?

**Comment by codediodeio** [comment]
Ok, this is because Ionic 3 uses RxJS 5.5, but this lib requires v6.2 Here is an easy fix and I will update the docs

```
npm i rxjs@latest rxjs-compat
```

**Comment by shriharip** [comment]
Yeah, it solved the issue.

**Comment by JakobGoeb** [comment]
i got the same issue, but the fix above is not working for me.
Actually the error is thrown, when i execute `geo.point(lat,lon) ` .

**Comment by JakobGoeb** [comment]
The error is slightly different: `Unhandled error TypeError: Cannot read properties of undefined (reading 'GeoPoint')`
