### ISSUE TITLE
Saving multiple geopoints on a single document

### ISSUE THREAD

**Issue by leonelngande** [codediodeio/geofirex#69]
Hi @codediodeio , 

First off thanks for this awesome library. Is it possible to add an example with respect to saving multiple geopoints on a single document to the readme?

Have gone through past issues and didn't find any related to this. Thanks again.

**Comment by codediodeio** [comment]
In version 0.1.0, the writes now happen via the main Firebase SDK, while geofirex just formats the data for you. Here's one way to do it. 
```
const cities = firebase.firestore().collection('cities');

const p1= geo.point(40, -119);
const p2 = geo.point(30, -111);

cities.add({ p1, p2 });
```
