### ISSUE TITLE
Orderby Query with Inequality Fails with GeoHash query

### ISSUE THREAD

**Issue by rohit-aq** [codediodeio/geofirex#75]
FirebaseError: Invalid query. You have a where filter with an inequality (<, <=, >, or >=) on field 'date_time' and so you must also use 'date_time' as your first Query.orderBy(), but your first Query.orderBy() is on field 'position.geohash' instead.

How I built my query

```
const stores = geo.collection('events', ref =>
        ref.orderBy('date_time')
        .where('date_time', '>=', currentTimeStamp)
        .where('privacy', '==', 'public')
    );

const query = stores.within(center, radius, field);
    let publicEvents = await geofirex.get(query)

```

**Comment by codediodeio** [comment]
That type of query will not work. The library works like this: 
```
  yourQuery
      .orderBy(`${field}.geohash`)
      .startAt(geohash)
      .endAt(end);
```

https://firebase.google.com/docs/firestore/query-data/queries#query_limitations

**Comment by bimix** [comment]
> 

You absolutely dont know what you talking about!
