### ISSUE TITLE
app.firestore is not a function

### ISSUE THREAD

**Issue by sultankhan** [codediodeio/geofirex#9]
I just started using this library with react-native and I am getting this error on geo.collections() method. Please suggest. Thanks,

<img width="335" alt="2018-07-19_0629" src="https://user-images.githubusercontent.com/4817749/42916635-b60d2e56-8b1f-11e8-942e-6f67c37f8e43.png">

**Comment by sultankhan** [comment]
Fixed!
Had to add import '@firebase/firestore' as well.

Worked perfect. Thanks.

**Comment by codediodeio** [comment]
Thanks, this should probably be updated in the docs as you need to have Firestore initialized in the project first.
